dist: bionic

language: node_js

node_js:
        - 13

services:
        - docker

before_install:
        - docker swarm init
        - scripts/installer.sh

script:
        - npm run test

after_failure:
        - scripts/dump_logs.sh

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01
