dist: bionic

language: node_js

node_js:
        - 13

services:
        - docker

before_install:
        - docker swarm init
        - scripts/installer.sh
        - echo 8df3b5a0-2653-42ff-9ae6-be616248c449 | docker login -u "echu888" --password-stdin 

script:
        - npm run test

after_failure:
        - scripts/dump_logs.sh

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01
