dist: bionic

language: node_js

node_js:
        - 13

services:
        - docker

before_install:
        - npm install -g Hiro-Nakamura/ab-cli
        - docker swarm init
        - scripts/installer.sh


script:
        - npm run test

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01

