dist: bionic

language: node_js

node_js:
        - 13

services:
        - docker

before_install:
        - docker swarm init
        - scripts/installer.sh
        # after running the installer, switch branches, and re-run npm install/build commands
        - scripts/git_checkout_branch.sh app_builder noArango
        - scripts/npm_install_versioned.sh app_builder 6.12.3 run build
        - scripts/git_checkout_branch.sh appdev-opsportal noArango
        - scripts/npm_install_versioned.sh appdev-opsportal 13 install

script:
        - npm run test

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01
