dist: bionic
language: node_js
node_js:
- 13
services:
- docker
env:
  global:
  - secure: "dj602yyJsSi0oS2VDjYPzBLyHily6VKIN9vZTYOPYu5POXB6uLx6c27SPTHnnycjduJeG2JepcKTqpQnEBZpbOdjNphVWtkbp7WtHEov37kpwN7Ff9LBjgFuDaszad2D0k2wI18bUdcz0c6uXoDQvcdgrkPZt7LgXN62ozARq1DE8PxXpPEszsEeQP+HZp2CAhzTIBL+/dgPn54dNDF6TcPB9k7eg2Lbxt590iSzw/sSmzzXb0mHaHRtgCzyVbR/yZZPKekNhjzLeOdMl3j1x9dS6JHaFSwlcbqyVWsW28xyMCsywuyMD9ahPbKXDrmT+T0UgtOtCUz6tc0f2JMCOa+hJ90mRLB4zujQNzs7LJL7ITawEcKkByzIaRGAk1RdZ2IM7tLwJjzCvNeSqikFNzNP4XzZtLIjBrWIbPkdjTYLwjodBn0L6wnuHjDCDNNpz/XEJIRHoh+okkluNqS0oVKwOIJo00GNNG8S4AjoPu/ahuAQLQS3JAfcsTowXmlvtLlTWjWh7C5N9q6mPeK+5dcte1hplQo/ACZWbV+yN8A6jtNSnPuAkflJSkWTBFKU+krKDTispnR5oZ6yvgES/dc11G8G4yvB9xJeXfNdkVzftffzhoIcGQsa7yjx5kKFSNP+xqn8gq67oYRBwKJfQrTw8620FMInvdoMKzDP/nU=" #DOCKER_USER
  - secure: "qW8p0Rl/jZ6h6IE2zaJHlSqKTup/PlDkP3oa4w/7lC1f7P2/yAuk130dEL6kSjL741cRal+nYAHZ1l7W3VRSOY2EuDU2iwCShxxZR7dIVHSCWycysSWTtlGAIeHFSpn0rJ5j9O3eebXZX0oJGhTsXSb2u8Qi/qxpJA6XVHs8l9AwHhl+P8XS0g29X6CADNf2d18b/7DsHamGnwXk/IJMxqSkos1+rko+Xv296rKJd6PqWVNJMhzVfBBG0W1p2TaTfko7VXIvfbygf/14Haf02ebGddUQMC4T3cGqhqSQOZIcQKoc4PSp/4frEusRKgUWcT/Dhwzo7wiU9JJV9DmIQI8L353p3ybX7L4O7t08Djy+fXNkRQkoZT5/uQYnzMuSeknCKA3PkymVT2qmzhffYlmEb2kVdVK1hllopYZH5vF/sPsakhUc+xxHhsyW3h22yX6At7kK7PRh0qsHzW+Gpub/nBg38/X5IIxsZWqFTDss4080jHxS9+eTCpzmWNW37q4KnzKQ/xwuIroWU5tSAtntiQet+2RTrWySGBZCUPbidjHmKiV2OjzVZpq8i4i/UhjfJ+zhSibcBAKa3nTZgXrOHMEtdlNgaJhsVRlNJZwxg0ziCT3eksjS878GVsTqA1MvS18VnxOuFypylcpJRiJgA6etvjL5s4gHEDRzqik=" #DOCKER_PW
before_install:
- docker swarm init
- scripts/installer.sh
- echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin
script:
- npm run test
after_failure:
- scripts/dump_logs.sh
notifications:
  slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01

