dist: bionic

language: node_js

node_js:
        - 9

services:
        - docker

before_install:
        #- npm install
        - npm install -g Hiro-Nakamura/ab-cli
        - docker swarm init
        - docker ps
        - scripts/installer.sh


script:
        #- npm run test
        - npm run installer-test

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01

