dist: bionic

language: node_js

node_js:
        - 13

services:
        - docker

before_install:
        - scripts/installer.sh
        - docker swarm init

script:
        - npm run test

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01
