dist: bionic

language: node_js

node_js:
        - 9

services:
        - docker

before_install:
        - npm install
          #- npm install -g Hiro-Nakamura/ab-cli

script:
        - npm run test
        #- npm run installer

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01

