name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Initialize docker swarm 
      - run: echo Hello, world!
        
      # Login to docker hub 
      - run: echo Hello, world!        
        
      # Run installer script 
      - run: echo Hello, world!
        
      # Run tests
      - run: echo Hello, world!
        
